### ISSUE TITLE
NL: range display incorrect whie rapid charging

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-Monitoring-System-3#634]
![20210603_110708-COLLAGE](https://user-images.githubusercontent.com/758844/120627758-e51ec880-c45b-11eb-9aa5-498ed6da7bad.jpg)

When rapid charging is in progress, the displayed range is crazy high! When rapid charging finishes, the range display reverts to normal

**Comment by drc38** [comment]
Try changing this parameter to `true` `MyConfig.GetParamValueBool("xnl", "soh.newcar", false)` which will then use the `maxGids` parameter along with `whPerGid` to do the calculation.

**Comment by drc38** [comment]
If the `soh.newcar` param is set to `false` the code is using `m_battery_energy_capacity` which is set by can message 0x59e for a 24kWh battery. Based on your experience with fast charging this can message may not be appropriately handled or may mean something slightly different, hence the weird values.

**Comment by glynhudson** [comment]
Thanks, I've just tried to apply the change you suggested, but It get the following error:

![Selection_444](https://user-images.githubusercontent.com/758844/121062757-67412100-c7bd-11eb-9997-6a29a93e4444.jpg)

**Comment by drc38** [comment]
That's the code snippet, from memory you can set it in the menu or use the shell command `config set` with the parameter and value

**Comment by glynhudson** [comment]
Ok got it, sorry I should have realised that. I managed to set it with 

`config set xnl soh.newcar true`

To view the Leaf config:

`config list xnl`

```
xnl (readable writeable)
  acvoltagemultiplier: 1.25
  cabintempoffset: .0
  canwrite: yes
  maxGids: 246
  modelyear: 2012
  newCarAh: 66
  soc.newcar: no
  soh.newcar: yes
  suffrange: 0
  suffsoc: 
```

I'll let you know how I get on next time I rapid charge. Cheers
